spring.application.name=PlanificadorTareasBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/PlanificadorTareas
spring.datasource.username=postgres
spring.datasource.password=Dragon10+*/
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=clave-secreta-larga-de-al-menos-32-caracteres-vetcare-2026
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
